"""Add Routes Model

Revision ID: 623157b08628
Revises: 
Create Date: 2022-01-08 17:14:00.928026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623157b08628'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('truck_id', sa.Integer(), nullable=True),
    sa.Column('driver', sa.String(length=255), nullable=True),
    sa.Column('customer', sa.String(length=255), nullable=True),
    sa.Column('loading', sa.String(length=255), nullable=True),
    sa.Column('unloading', sa.String(length=255), nullable=True),
    sa.Column('received', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('payment', sa.String(length=15), nullable=True),
    sa.Column('debt', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('date_posted', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    # ### end Alembic commands ###
